// action của sign in reducer
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const SIGN_OUT = 'SIGN_OUT';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const LOAD_AVATAR_SUCCESS = 'LOAD_AVATAR_SUCCESS';
export const FETCH_NEW_MESSAGE_SUCCESS = 'FETCH_NEW_MESSAGE_SUCCESS';
export const VIEW_MESSAGE = 'VIEW_MESSAGE';

// action của admin reducer
export const LOAD_ALL_INFO_SUCCESS = 'LOAD_ALL_INFO_SUCCESS'; 
export const LOAD_ALL_INFO_FAIL = 'LOAD_ALL_INFO_FAIL'; 
export const ADMIN_KNOW_ERROR = 'ADMIN_KNOW_ERROR';

export const ADMIN_KNOW_SUCCESS = 'ADMIN_KNOW_SUCCESS';
export const ADMIN_OPEN_EDIT_PROFILE = 'ADMIN_OPEN_EDIT_PROFILE';
export const ADMIN_UPDATE_PROFILE_SUCCESS = 'ADMIN_UPDATE_PROFILE_SUCCESS';
export const ADMIN_UPDATE_PROFILE_ERROR = 'ADMIN_UPDATE_PROFILE_ERROR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CHANGE_ADMIN_REDIRECT_PATH = 'CHANGE_ADMIN_REDIRECT_PATH';

// action của partner reducer
export const CREATE_EMPLOY_INFO_SUCCESS = 'CREATE_EMPLOY_INFO_SUCCESS';
export const CREATE_EMPLOY_INFO_FAIL = 'CREATE_EMPLOY_INFO_FAIL';
export const PARTNER_CLOSE_DIALOG = 'PARTNER_CLOSE_DIALOG';