export const suggestions = [
    { value: 'framgia' },
    { value: 'samsung' },
    { value: 'php' },
    { value: 'html' },
    { value: 'css' },
    { value: 'laravel' },
    { value: 'front end' },
    { value: 'back end' },
    { value: 'nodejs' },
    { value: 'angular' },
    { value: 'react' },
    { value: 'vuejs' },
    { value: 'docker' },
]